verbose: true
instrumentation:
    extension: .js
    root: ./src
    default-excludes: true
    include-all-sources: true
    excludes: ['**/*Form.js', '**/modules/camerasmanager/*', '**/internal-plugins/rflink/*']
    embed-source: false
    variable: __coverage__
    compact: true
    preserve-comments: false
    complete-copy: false
    save-baseline: false
reporting:
    print: summary
    reports:
        - lcov
    dir: ./coverage
    watermarks:
        statements: [50, 80]
        lines: [50, 80]
        functions: [50, 80]
        branches: [50, 80]
hooks:
    hook-run-in-context: false
    post-require-hook: null
