#!/bin/bash

if [ -e /tmp/hautomation-config.json ]
then
    rm -Rf /var/hautomation/data/config.json
    mv /tmp/hautomation-config.json /var/hautomation/data/config.json
fi

systemctl daemon-reload
systemctl enable hautomation
systemctl restart hautomation
echo "Hautomation has been successfully installed ! Open browser and go to https://me.hautomation-io.com/ to start ! (on first installation, start can take some times to install dependencies)"
