#!/bin/bash

if [ -e /tmp/hautomation-config.json ]
then
    rm -Rf /var/hautomation/data/config.json
    mv /tmp/hautomation-config.json /var/hautomation/data/config.json
fi

systemctl daemon-reload
systemctl enable hautomation
systemctl restart hautomation
echo ""
echo "Hautomation has been successfully installed !"
echo ""
echo "How to use ?"
echo "Open a web browser on your computer and go to https://me.hautomation-io.com/ to start, with the username 'admin' and password 'admin' ! (on first installation, start can take some times to install dependencies, wait for some minutes if it dosen't works)"
echo ""
